export {default as Home} from "./Home"
export {default as Landing} from "./Landing"
export {default as MainPage} from "./MainPage"
export {default as SingleProduct} from "./SingleProduct"
export {default as Cart} from "./Cart"